"""Materialise the four-mask validated far-distance=.25 source-route blend."""
from __future__ import annotations

import json
from pathlib import Path
import pandas as pd

import source_route_distance_adaptive as m

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "research"
OUT = ROOT / "outputs"
NAME = "model_dani_source_expert_route_v2_distance_adaptive_f25_submission.csv"


def main() -> None:
    path, meta = m.apply_private(outname=NAME, far_alpha=0.25)
    # The independent four-mask audit is generated by the sibling scripts;
    # include its exact pooled figures in a short, standalone report.
    metrics = pd.read_csv(R / "source_route_v2_piecewise_grid_20260905.csv")
    row = metrics[(metrics.route == "crop_hier_n1_p67") & (metrics.policy == "fixed_050_040_025")].iloc[0]
    meta["audit_masks"] = "0,1,2,70404"
    meta["audit_pooled_rmse"] = float(row.pooled_rmse)
    meta["audit_per_seed"] = str(row.per_seed)
    (OUT / (path.stem + "_metadata.json")).write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    report = [
        "# Source-route distance-adaptive f25 candidate",
        "",
        "Fixed alpha rule: .50 for nearest visible same-crop numeric AOI distance <=2, .40 for 3--8, .25 for >8 or no peer.",
        "",
        f"Four-mask pooled audit RMSE: {float(row.pooled_rmse):.6f}; per seed: {row.per_seed}.",
        "",
        f"Candidate: `{path.relative_to(ROOT).as_posix()}`",
        "",
        json.dumps(meta, ensure_ascii=False, indent=2),
        "",
        "No old output was overwritten and no submission was uploaded.",
    ]
    (R / "source_route_distance_adaptive_f25_report.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print(json.dumps(meta, ensure_ascii=False, indent=2), flush=True)


if __name__ == "__main__":
    main()
