"""Leakage-safe source experts with spatial/date acquisition routing (v2).

This research runner extends ``source_expert_q1`` in two ways:

* three HGB experts are trained on honest pseudo-gaps, one per acquisition
  source (S2/Landsat/MODIS);
* the hidden source is routed from observable same-date neighbouring AOIs
  (crop-aware numeric AOI distance), backed off to the usual schedule
  posterior.  A soft, sharpened posterior is also evaluated.

The script deliberately keeps the true source only in an evaluation sidecar.
It evaluates independent private-like masks (seeds 0, 1 and 70404), reports
cohort/year/source/distance slices, and can materialise a separate full-gap
candidate after the audits.  Existing artifacts are never overwritten.
"""
from __future__ import annotations

import hashlib
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA = Path(r"C:/Users/kmaxc/Documents/Codex/2026-09-04/ml/work/cosmo_latest_20260904")
R = ROOT / "research"
OUT = ROOT / "outputs"

# Reuse the already audited source-expert fit and mask construction.  Importing
# these functions has no side effects (their ``main`` is guarded).
sys.path.insert(0, str(R))
import source_expert_q1 as q1  # noqa: E402
from evaluate_private_cohort_blend import make_holdout  # noqa: E402
from overnight_source_eval import _predict_matrix, _source_labels  # noqa: E402

ID, DATE, TARGET, GAP = "anon_polygon_id", "date", "primary_ndvi", "is_synthetic_gap"
SOURCES = ("s2", "landsat", "modis")
SRC_TO_INT = {s: i for i, s in enumerate(SOURCES)}
ROUTE_RADII = (1, 2, 4, 8, 16, 32)


def _rmse(y: np.ndarray, p: np.ndarray) -> float:
    y = np.asarray(y, float); p = np.asarray(p, float)
    ok = np.isfinite(y) & np.isfinite(p)
    return float(np.sqrt(np.mean((p[ok] - y[ok]) ** 2))) if ok.any() else np.nan


def _sha(path: Path) -> str:
    h = hashlib.sha256(); h.update(path.read_bytes()); return h.hexdigest()


def _masked_private(pr: pd.DataFrame, hold: np.ndarray) -> tuple[pd.DataFrame, np.ndarray]:
    """Mask organiser gaps and an outer holdout, preserving only observables."""
    p = pr.copy().reset_index(drop=True)
    p[DATE] = pd.to_datetime(p[DATE])
    actual = p[GAP].fillna(False).astype(bool).to_numpy()
    gaps = actual | np.asarray(hold, bool)
    for c in q1.DYNAMIC:
        if c in p:
            p.loc[gaps, c] = np.nan
    p.loc[gaps, GAP] = True
    return p, gaps


def _baseline_for_seed(seed: int, pr: pd.DataFrame, hold: np.ndarray) -> pd.DataFrame:
    """Load the strongest already-built baseline for a validation mask."""
    if int(seed) == 70404:
        base = pd.read_csv(R / "private_cohort_blend_holdout_predictions.csv",
                           parse_dates=[DATE], low_memory=False)
        # The production leader is ext40 + 0.12*(peer-ext40) on history only.
        b = base[[ID, DATE, "ext40", "n16_c60_r125_k2"]].copy()
        yrs = pd.to_datetime(b[DATE]).dt.year.to_numpy(int)
        b["baseline"] = b["ext40"].to_numpy(float) + np.where(
            yrs < 2025, .12, 0.0
        ) * np.nan_to_num(
            b["n16_c60_r125_k2"].to_numpy(float) - b["ext40"].to_numpy(float),
            nan=0.0,
        )
        return b[[ID, DATE, "baseline"]]
    # Independent masks 0/1 were generated by the meta-residual runner and
    # contain the same ext40/peer component.  Keep only the requested rows.
    allb = pd.read_csv(R / "meta_residual_v2_independent_predictions.csv",
                       parse_dates=[DATE], low_memory=False)
    b = allb.loc[allb["mask_seed"].eq(int(seed)),
                 [ID, DATE, "ext40", "n16_c60_r125_k2"]].copy()
    if b.empty:
        raise FileNotFoundError(f"no saved baseline for seed {seed}")
    yrs = pd.to_datetime(b[DATE]).dt.year.to_numpy(int)
    b["baseline"] = b["ext40"].to_numpy(float) + np.where(
        yrs < 2025, .12, 0.0
    ) * np.nan_to_num(
        b["n16_c60_r125_k2"].to_numpy(float) - b["ext40"].to_numpy(float),
        nan=0.0,
    )
    return b[[ID, DATE, "baseline"]]


def _neighbor_counts(pm: pd.DataFrame, gaps: np.ndarray,
                     qkeys: pd.DataFrame) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return crop/all source count arrays and nearest crop distance.

    Source labels are computed after masking, so only visible rows can enter
    these arrays.  Date dictionary lookup avoids an O(n_query*n_frame) scan.
    """
    d = pm.reset_index(drop=True).copy(); d[DATE] = pd.to_datetime(d[DATE])
    src = np.select([d["s2_ndvi"].notna(), d["landsat_ndvi"].notna(),
                     d["modis_ndvi"].notna()], [0, 1, 2], -1)
    idnum = pd.to_numeric(d[ID].astype(str).str.extract(r"(\d+)", expand=False),
                          errors="coerce").fillna(-1).to_numpy(int)
    dates = d[DATE].to_numpy(); crops = d["crop_type"].fillna("unknown").astype(str).to_numpy()
    vis = np.flatnonzero((~np.asarray(gaps, bool)) & (src >= 0))
    bydate = {dt: np.asarray(ix, dtype=int)
              for dt, ix in pd.Series(vis, index=vis).groupby(dates[vis])}
    qkeys = qkeys.reset_index(drop=True); qdates = pd.to_datetime(qkeys[DATE]).to_numpy()
    qids = pd.to_numeric(qkeys[ID].astype(str).str.extract(r"(\d+)", expand=False),
                         errors="coerce").fillna(-1).to_numpy(int)
    qcrops = qkeys.get("crop_type", pd.Series("unknown", index=qkeys.index)).fillna("unknown").astype(str).to_numpy()
    # Arrays indexed [query, source] for each radius are returned as a stack.
    crop_counts = np.zeros((len(qkeys), len(ROUTE_RADII), 3), float)
    all_counts = np.zeros_like(crop_counts)
    nearest = np.full((len(qkeys),), np.inf, float)
    for n, (dt, aid, crop) in enumerate(zip(qdates, qids, qcrops)):
        z0 = np.asarray(bydate.get(dt, np.empty(0, int)), dtype=int)
        for rj, radius in enumerate(ROUTE_RADII):
            z = z0[np.abs(idnum[z0] - aid) <= radius]
            if len(z):
                all_counts[n, rj] = np.bincount(src[z], minlength=3)
            zz = z[crops[z] == crop] if len(z) else z
            if len(zz):
                crop_counts[n, rj] = np.bincount(src[zz], minlength=3)
                nearest[n] = min(nearest[n], float(np.min(np.abs(idnum[zz] - aid))))
    return crop_counts, all_counts, nearest


def _route_variants(crop_counts: np.ndarray, all_counts: np.ndarray,
                    posterior: np.ndarray) -> dict[str, np.ndarray]:
    """Build hard/soft routes without observing hidden labels."""
    n = len(posterior); post_mode = np.argmax(posterior, axis=1)
    out: dict[str, np.ndarray] = {"post_mode": post_mode.copy()}
    # At the first radius with any same-crop peer, use that mode.  This gives
    # high precision on near AOI pairs while retaining broad fallback.
    for min_n in (1, 2, 3):
        for min_purity in (0.0, 0.67, 0.8):
            route = post_mode.copy(); used = np.zeros(n, bool)
            for rj in range(crop_counts.shape[1]):
                c = crop_counts[:, rj]; nn = c.sum(1)
                purity = c.max(1) / np.maximum(1.0, nn)
                take = (~used) & (nn >= min_n) & (purity >= min_purity)
                route[take] = np.argmax(c[take], axis=1); used |= take
            out[f"crop_hier_n{min_n}_p{int(min_purity*100):02d}"] = route
    # Soft all-neighbour counts at each radius.  A mild posterior pseudocount
    # and power sharpen are both observable and robust to one noisy peer.
    for rj, radius in enumerate(ROUTE_RADII):
        for typ, c in (("crop", crop_counts[:, rj]), ("all", all_counts[:, rj])):
            for lam in (0.0, 0.25, 1.0):
                q = c + lam * posterior
                bad = q.sum(1) <= 0
                q[bad] = posterior[bad]
                q /= q.sum(1, keepdims=True)
                for power in (1.0, 2.0, 4.0):
                    w = np.power(np.clip(q, 1e-9, 1.0), power)
                    w /= w.sum(1, keepdims=True)
                    out[f"soft_{typ}_r{radius}_l{lam:g}_p{power:g}"] = w
    return out


def _fit_one(seed: int, tr: pd.DataFrame, pr: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Fit source experts for one outer mask and return row/metric tables."""
    hold = make_holdout(pr, seed=int(seed))
    pm, gaps_pr = _masked_private(pr, hold)
    # q1's builder handles the sorted train+private reference and honest OOF
    # expert fits.  ``ep_ref`` is aligned to sorted reference gap rows.
    ref, gaps_ref, sref, _pm_unused, _gaps_unused = q1._make_masked_ref(tr, pr, hold)
    models, ep_ref, _ = q1._fit_experts(ref, gaps_ref, sref)
    qref = ref.loc[gaps_ref, [ID, DATE]].copy().reset_index(drop=True)
    qref[["e_s2", "e_landsat", "e_modis"]] = ep_ref
    qkeys = pr.loc[hold, [ID, DATE, "crop_type"]].copy().reset_index(drop=True)
    qkeys[DATE] = pd.to_datetime(qkeys[DATE])
    q = qkeys.merge(qref, on=[ID, DATE], how="left", validate="one_to_one")
    if q[["e_s2", "e_landsat", "e_modis"]].isna().any().any():
        raise RuntimeError(f"expert key alignment failed for seed {seed}")
    # Observable schedule posterior from train + masked private rows.
    pmatrix, _ = _predict_matrix(pm, train=tr, family="base", k=8, degree=1,
                                 bin_days=30, date_weight=1.0)
    pmap = pmatrix.set_index("row_index")
    qi = np.flatnonzero(hold)
    q["post_s2"] = [pmap.loc[i, "p_s2"] if i in pmap.index else 1/3 for i in qi]
    q["post_landsat"] = [pmap.loc[i, "p_landsat"] if i in pmap.index else 1/3 for i in qi]
    q["post_modis"] = [pmap.loc[i, "p_modis"] if i in pmap.index else 1/3 for i in qi]
    post = q[["post_s2", "post_landsat", "post_modis"]].to_numpy(float)
    post = np.where(np.isfinite(post), post, 1/3); post /= post.sum(1, keepdims=True)
    # Source sidecar is used solely to score; it is not passed to any model.
    q["truth"] = pr.loc[hold, TARGET].to_numpy(float)
    q["true_src"] = _source_labels(pr)[hold]
    q["year"] = q[DATE].dt.year.astype(int)
    q["cohort"] = np.where(q[ID].astype(str).isin(set(tr[ID].astype(str))), "shared", "new")
    # Current leader baseline for exactly this mask.
    b = _baseline_for_seed(seed, pr, hold)
    q = q.merge(b, on=[ID, DATE], how="left", validate="one_to_one")
    if q.baseline.isna().any(): raise RuntimeError(f"baseline alignment failed seed {seed}")
    # Same-date crop-aware route features.
    cc, ac, near = _neighbor_counts(pm, gaps_pr, qkeys)
    q["near_dist"] = near
    variants = _route_variants(cc, ac, post)
    E = q[["e_s2", "e_landsat", "e_modis"]].to_numpy(float)
    y = q.truth.to_numpy(float); B = q.baseline.to_numpy(float)
    # Evaluate baseline, posterior family and source route blends.  ``W``
    # variants are posterior matrices; hard variants are integer routes.
    recs: list[dict[str, object]] = []
    pred_store: dict[str, np.ndarray] = {"baseline": B}
    recs.append({"seed": seed, "method": "baseline", "n": len(y), "rmse": _rmse(y, B)})
    for name, v in variants.items():
        if v.ndim == 1:
            psrc = E[np.arange(len(E)), v.astype(int)]
            pred_store[name] = psrc
            recs.append({"seed": seed, "method": name, "n": len(y),
                         "rmse": _rmse(y, psrc)})
            # Conservative blend grid; 0.4 is selected only after pooled audit.
            for alpha in (0.2, 0.3, 0.4, 0.5):
                p = (1-alpha)*B + alpha*psrc
                nm = f"blend_{name}_{alpha:.2f}"; pred_store[nm] = p
                recs.append({"seed": seed, "method": nm, "n": len(y), "rmse": _rmse(y, p)})
        else:
            psrc = np.sum(v * E, axis=1)
            pred_store[name] = psrc
            recs.append({"seed": seed, "method": name, "n": len(y),
                         "rmse": _rmse(y, psrc)})
            for alpha in (0.2, 0.3, 0.4, 0.5):
                p = (1-alpha)*B + alpha*psrc
                nm = f"blend_{name}_{alpha:.2f}"; pred_store[nm] = p
                recs.append({"seed": seed, "method": nm, "n": len(y), "rmse": _rmse(y, p)})
    # Add source/year/cohort/distance slices for the stable shortlist.
    shortlist = ["baseline", "blend_post_mode_0.40",
                 "blend_crop_hier_n1_p67_0.40",
                 "blend_soft_all_r1_l0_p4_0.40",
                 "blend_soft_crop_r1_l0_p4_0.40",
                 "blend_soft_all_r2_l0_p4_0.40",
                 "blend_soft_all_r32_l0_p4_0.40"]
    for method in shortlist:
        if method not in pred_store: continue
        p = pred_store[method]
        for grp, gg in [("all", np.ones(len(q), bool)),
                        ("history", q.year.to_numpy() < 2025),
                        ("2025", q.year.to_numpy() == 2025),
                        ("new", q.cohort.to_numpy() == "new"),
                        ("shared", q.cohort.to_numpy() == "shared"),
                        ("near", np.isfinite(near) & (near <= 2)),
                        ("mid", np.isfinite(near) & (near > 2) & (near <= 8)),
                        ("far_or_none", (~np.isfinite(near)) | (near > 8))]:
            if gg.any():
                recs.append({"seed": seed, "method": method, "slice": grp,
                             "n": int(gg.sum()), "rmse": _rmse(y[gg], p[gg])})
        for src in SOURCES:
            gg = q.true_src.to_numpy() == src
            if gg.any():
                recs.append({"seed": seed, "method": method, "slice": f"source_{src}",
                             "n": int(gg.sum()), "rmse": _rmse(y[gg], p[gg])})
    # Keep predictions needed for pooled analysis in a compact long table.
    keep = ["baseline", "blend_post_mode_0.40", "blend_crop_hier_n1_p67_0.40",
            "blend_soft_all_r1_l0_p4_0.40", "blend_soft_crop_r1_l0_p4_0.40",
            "blend_soft_all_r2_l0_p4_0.40", "blend_soft_all_r32_l0_p4_0.40"]
    rows = q[[ID, DATE, "truth", "true_src", "year", "cohort", "near_dist"]].copy()
    for nm in keep:
        if nm in pred_store: rows[nm] = pred_store[nm]
    rows["seed"] = int(seed)
    return rows, pd.DataFrame(recs)


def _fit_final_candidate(tr: pd.DataFrame, pr: pd.DataFrame) -> Path:
    """Fit experts against only real gaps and write a separate 3,112-row CSV."""
    actual = pr[GAP].fillna(False).astype(bool).to_numpy()
    # Build a synthetic ``hold`` of no extra rows; q1's helper still masks
    # actual gaps and returns expert predictions for them.
    ref, gaps_ref, sref, pm, gaps_pr = q1._make_masked_ref(tr, pr, np.zeros(len(pr), bool))
    models, ep_ref, _ = q1._fit_experts(ref, gaps_ref, sref)
    qref = ref.loc[gaps_ref, [ID, DATE]].copy().reset_index(drop=True)
    qref[["e_s2", "e_landsat", "e_modis"]] = ep_ref
    # Schedule posterior and crop-aware route use only real hidden gaps.
    pmm, gaps = _masked_private(pr, np.zeros(len(pr), bool))
    pmatrix, _ = _predict_matrix(pmm, train=tr, family="base", k=8, degree=1,
                                 bin_days=30, date_weight=1.0)
    pmap = pmatrix.set_index("row_index")
    qkeys = pr.loc[actual, [ID, DATE, "crop_type"]].copy().reset_index(drop=True)
    qkeys[DATE] = pd.to_datetime(qkeys[DATE]); qi = np.flatnonzero(actual)
    q = qkeys.merge(qref, on=[ID, DATE], how="left", validate="one_to_one")
    post = np.column_stack([[pmap.loc[i, c] if i in pmap.index else 1/3 for i in qi]
                            for c in ("p_s2", "p_landsat", "p_modis")])
    post = np.where(np.isfinite(post), post, 1/3); post /= post.sum(1, keepdims=True)
    cc, ac, _ = _neighbor_counts(pmm, gaps, qkeys)
    rv = _route_variants(cc, ac, post)
    # Conservative fixed route: crop-aware first available peer, min purity
    # 0.67, then schedule posterior mode.  This was selected by pooled masks.
    route = rv["crop_hier_n1_p67"]
    E = q[["e_s2", "e_landsat", "e_modis"]].to_numpy(float)
    psrc = E[np.arange(len(E)), route]
    # The source expert is blended into the existing ext40/history-peer12
    # candidate.  Recompute that baseline from the saved full-gap components.
    basepath = OUT / "model_dani_extwide40_v3_30_peerblend12_history_submission.csv"
    base = pd.read_csv(basepath, parse_dates=[DATE], low_memory=False)
    bmap = base.set_index([ID, DATE])["primary_ndvi_pred"]
    b = np.asarray([bmap.get((i, d), np.nan) for i, d in q[[ID, DATE]].itertuples(index=False, name=None)], float)
    if not np.isfinite(b).all(): raise RuntimeError("full baseline key alignment failed")
    alpha = 0.40
    pred = np.clip((1-alpha)*b + alpha*psrc, -0.2, 1.1)
    out = q[[ID, DATE]].copy(); out["primary_ndvi_pred"] = pred
    out[DATE] = pd.to_datetime(out[DATE]).dt.strftime("%Y-%m-%d")
    path = OUT / "model_dani_source_expert_route_v2_submission.csv"
    out.to_csv(path, index=False, float_format="%.9f")
    meta = {"candidate": path.name, "formula": "0.60*history_peer12 + 0.40*source_expert[crop-aware same-date route; n>=1,purity>=0.67]", "rows": int(len(out)), "actual_gaps": int(actual.sum()), "sha256": _sha(path), "finite": bool(np.isfinite(pred).all()), "unique_keys": int(out[[ID, DATE]].drop_duplicates().shape[0]), "production_baseline_overwritten": False}
    path.with_name(path.stem + "_metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return path


def main() -> None:
    t0 = time.time()
    tr = pd.read_csv(DATA / "train_dataset.csv", parse_dates=[DATE], low_memory=False)
    pr = pd.read_csv(DATA / "private_features.csv", parse_dates=[DATE], low_memory=False)
    pr[GAP] = pr[GAP].fillna(False).astype(bool)
    all_rows = []; all_metrics = []
    for seed in (0, 1, 70404):
        print(f"fit source experts seed={seed}", flush=True)
        rr, mm = _fit_one(seed, tr, pr)
        all_rows.append(rr); all_metrics.append(mm)
        print(mm[(mm.method == "baseline") | mm.method.str.contains("crop_hier_n1_p67_0.40")].to_string(index=False), flush=True)
    rows = pd.concat(all_rows, ignore_index=True); metrics = pd.concat(all_metrics, ignore_index=True)
    rows.to_csv(R / "source_expert_route_v2_rows.csv", index=False, float_format="%.9f")
    metrics.to_csv(R / "source_expert_route_v2_metrics.csv", index=False, float_format="%.9f")
    # Pooled RMSE over independent rows (row-level concatenation, not mean of
    # fold RMSEs).  Report only methods present in all three masks.
    predcols = [c for c in rows.columns if c.startswith("blend_") or c == "baseline"]
    pooled = []
    for c in predcols:
        z = rows[["seed", "truth", c]].dropna();
        if set(z.seed.astype(int)) != {0, 1, 70404}: continue
        pooled.append({"method": c, "n": len(z), "rmse": _rmse(z.truth.to_numpy(), z[c].to_numpy()),
                       "per_seed": ";".join(f"{s}:{_rmse(g.truth.to_numpy(),g[c].to_numpy()):.6f}" for s,g in z.groupby("seed"))})
    pool = pd.DataFrame(pooled).sort_values("rmse")
    pool.to_csv(R / "source_expert_route_v2_pooled.csv", index=False, float_format="%.9f")
    report = ["# Source-expert route v2 audit", "", "Masks: private-like seeds 0, 1, 70404; true source is evaluation-only.", "", "## Pooled shortlist", "", pool.head(20).to_string(index=False), "", "## Slice metrics (all rows)", "", metrics.to_string(index=False), ""]
    try:
        path = _fit_final_candidate(tr, pr)
        report += [f"Final separate candidate: `{path.relative_to(ROOT).as_posix()}`", f"SHA256: `{_sha(path)}`", ""]
    except Exception as exc:
        report += [f"Final candidate not materialized: {type(exc).__name__}: {exc}", ""]
    report += [f"Elapsed seconds: {time.time()-t0:.1f}", "No existing candidate or input file was overwritten."]
    (R / "source_expert_route_v2_report.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print(pool.head(20).to_string(index=False), flush=True)


if __name__ == "__main__":
    main()
